### ISSUE TITLE
verify with `allowedIss` will be ignored if payload without iss data

### ISSUE THREAD

**Issue by liaosankai** [nearform/fast-jwt#182]
Options with `allowedIss` to verify token. I think it should throw error if payload without iss value. Shouldn't it?

```js
// file: test/example.spec.js

const { test } = require('tap')
const { createSigner, createVerifier } = require('../src')
const signSync = createSigner({ key: 'secret' })
const verifySync = createVerifier({ key: 'secret', allowedIss: 'foo.bar' })

// passing
test('token payload with iss value', async (t) => {
  const tokenPayloadWithIss = signSync({ a: 1, b: 2, c: 3, iss: 'bad' })
  t.throws(
    () => {
      verifySync(tokenPayloadWithIss, (err) => {
        console.log(err)
      })
    },
    {
      code: 'FAST_JWT_INVALID_CLAIM_VALUE',
      message: 'The iss claim value is not allowed.'
    }
  )
  t.end()
})

// failing
test('token payload without iss value', async (t) => {
  const tokenPayloadWithoutIss = signSync({ a: 1, b: 2, c: 3 })
  t.throws(() => {
    verifySync(
      tokenPayloadWithoutIss,
      (err) => {
        console.log(err)
      },
      {
        code: 'FAST_JWT_INVALID_CLAIM_VALUE',
        message: 'The iss claim value is not allowed.'
      }
    )
  })
  t.end()
})
```
and it also happen verify with `allowedJti`, `allowedAud`, `allowedSub`, and `allowedNonce`

**Comment by zbo14** [comment]
Hmm it looks like [validation is intentionally skipped](https://github.com/nearform/fast-jwt/blob/master/src/verifier.js#L201) if the claim key isn't included.

**Comment by mcollina** [comment]
Ah yes, there are quite a few implementations out there without a claim.

I think you might have this check done in your code, or maybe we can add an option to throw instead of skip if it's missing?

Cc @ShogunPanda

**Comment by ShogunPanda** [comment]
Well, when I initially designed this I followed jsonwebtoken approach and thus I interpreted the word "allowed" literally.

@mcollina rather than adding a `skip` option, I would rather add a new set of `required*` options so that the two approaches can be mixed.

**Comment by liaosankai** [comment]
thank you all for suggest, and I will try check it in my code before official solutions release  :)

**Comment by hails** [comment]
Hey there, I've [created a pull request addressing this issue](https://github.com/nearform/fast-jwt/pull/184), taking @ShogunPanda 's suggestion on having the possibility of mixing both approaches.
