### ISSUE TITLE
It's not possible to run the benchmarks, issues with `cronometro` and ES Modules

### ISSUE THREAD

**Issue by hails** [nearform/fast-jwt#185]
Currently, it's not possible to run the benchmark scripts.
When you try to run them (for example with `npm run benchmark:decode`), Node.js will refuse to execute the files with the following error:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/hails/src/github.com/nearform/fast-jwt/node_modules/cronometro/dist/index.js from /Users/hails/src/github.com/nearform/fast-jwt/benchmarks/utils.js not supported.
Instead change the require of index.js in /Users/hails/src/github.com/nearform/fast-jwt/benchmarks/utils.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/hails/src/github.com/nearform/fast-jwt/benchmarks/utils.js:3:20)
    at Object.<anonymous> (/Users/hails/src/github.com/nearform/fast-jwt/benchmarks/decode.js:3:39) {
  code: 'ERR_REQUIRE_ESM'
}
```
The problem occurs because [`cronometro`](https://github.com/ShogunPanda/cronometro) is defined as an ES Module and and is not compatible with CommonJS. Instead of just using `require`, we should use the `dynamic import` approach, as described in [this gist by @ShogunPanda](https://gist.github.com/ShogunPanda/fe98fd23d77cdfb918010dbc42f4504d)

**Comment by mcollina** [comment]
I think this was updated automatically without testing by dependabot. Could you update them to esm?

**Comment by simoneb** [comment]
let's run benchmarks in CI so we catch these as well
