### ISSUE TITLE
Cache keys

### ISSUE THREAD

**Issue by emilbayes** [nearform/fast-jwt#21]
Hi!

Was looking through the crypto of this module and one thing I was wondering about was the rationale for the algorithm used to protect the cache:

https://github.com/nearform/fast-jwt/blob/b0893cfab917065b3acdb52b5db23bd9257673aa/src/utils.js#L45-L59

Looking through the usage in the code, it seems that the key into the cache is always the hash of the full JWT token. The algorithm for hashing the tokens changes depending on the algorithm used in the header of the token. The accompanying blog post mentions:

> To guarantee that the cache data is not compromised in case of unauthorized memory access, tokens are indexed in cache using a hashing algorithm which is chosen depending on the token encryption. For instance, HS384 encrypted token are hashed using the SHA384 algorithm, while EdDSA encrypted tokens with Ed448 curve are hashed using the SHAKE256 algorithm.

However, it doesn't mention why it's important to change the hash function.

The same function could be used for all key types, and simplify the code with less branches, using a HMAC with a random key generated on startup (fine since this is an in-memory cache). This would also protect against potential timing attacks in the lookup, since the key into the cache now uses a secret (I don't immediately see how one could find a distinguisher to perform such an attack with the current implementation, but maybe there's something I couldn't think of);

```js
const { createHmac } = require('crypto')

const blindingKey = crypto.randomBytes(64) // Key / block size for BLAKE2s-256

module.exports = function key (data) {
  return createHmac('blake2s256', blindingKey).update(data).digest('hex')
}
```

~~Something like SipHash would also be an ideal candidate for this, and yield much smaller keys,  saving memory. However I don't think that's available in core~~

Obviously there's a reason why you wrote it the way you did, and I could have completely misunderstood!

**Comment by mcollina** [comment]
Essentially to respect the spec and requirements of the issuer of the token. They ask for a specific hash function to be used, and we follow.

I can see how using an hmac scheme with a new key at every startup would make this as safe if not safer. It's probably only a matter of benchmarking. Decoding the token can be quite expensive, but also calculating two hashes for the hmac is.

**Comment by panva** [comment]
More to the why [here](https://github.com/nearform/fast-jwt/issues/8#issuecomment-580711284). Basically follow the practice of not mixing hash algorithms. Stay within on the same level.

**Comment by emilbayes** [comment]
What spec is this? The hash function for turning the signed message into a scalar?

I think the above code is already mixing hashing algorithms, at least for Ed25519 (SHA-512, but above it branches to SHAKE-256/114).

An adversary here would essentially have to perform a preimage attack before the cache TTL expires

**Comment by mcollina** [comment]
https://tools.ietf.org/html/rfc7515#section-4.1.1 specifies which algorithm is used to sign a JWT token. We keep honouring that requests in this package.

**Comment by emilbayes** [comment]
Thanks for providing the links! :) I learnt something new
