### ISSUE TITLE
asn1.js with native Buffer and BigInt

### ISSUE THREAD

**Issue by Uzlopak** [nearform/fast-jwt#234]
I saw that fast-jwt does use asn1.js. I forked it and made it work with native Buffer and native BigInt. I dont think that it has big performance gains. But maybe this is something you want to use instead of the original package?

https://github.com/Uzlopak/asn1.js

**Comment by ShogunPanda** [comment]
Back then it was the fastest way to decode those structures. If you found a more neat and native way, absolutely go for it!

**Comment by Uzlopak** [comment]
I dreamt today about asn1.js. crazy. Well according to my dream we can replace it with some custom functions. Will investigate it further...

**Comment by brettwillis** [comment]
+1 for this. `asn1.js` is pretty big and also depends on `bn.js` which more than doubles the size of this package.

**Comment by Uzlopak** [comment]
@synapse 

I am currently sick. But i can release it as a module.

**Comment by synapse** [comment]
Cool thanks @Uzlopak , reopening it. Please let me know when ready

**Comment by brettwillis** [comment]
I've moved on from this as this stage so I don't mind either way. However you could take inspiration from how the `jose` package parses secrets from different formats with small, application-specific code without these huge dependencies. Up to you 👍

**Comment by simoneb** [comment]
@brettwillis NPM says that asn1.js is around [48kB](https://www.npmjs.com/package/asn1.js/v/4.10.1?activeTab=code), it doesn't sound terribly huge to me
