### ISSUE TITLE
Custom exp claim priority

### ISSUE THREAD

**Issue by chgmikeww** [nearform/fast-jwt#254]
Hello,

I have a requirement for custom exp claim. However I still want to have a default available.
Custom exp claim was introduced here https://github.com/nearform/fast-jwt/issues/58

Would it be more reasonable to prioritise it like this?
```
const finalPayload = {
    ...payload,
    ...fixedPayload,
    iat: noTimestamp ? undefined : Math.floor(iat / 1000),
    exp: payload.exp ? payload.exp : (expiresIn ? Math.floor((iat + expiresIn) / 1000 : undefined)),
    nbf: notBefore ? Math.floor((iat + notBefore) / 1000) : undefined
  }
```

This will cater for the original requirement since custom exp was only working when there were no default expiresIn values.
At the same time increasing or reducing the default timeout will also be an option.

Regards,
Mike.

**Comment by simoneb** [comment]
Good idea. Would you like to send a Pull Request?
