### ISSUE TITLE
Does the SignerOptions allow the `aud` to be an array of strings?

### ISSUE THREAD

**Issue by s25g5d4** [nearform/fast-jwt#262]
Regarding the documentation, the `aud` property in SignerOptions should accept an array of strings, but [its type](https://github.com/nearform/fast-jwt/blob/688f2373df8e1c0a5d76c421bb5510d0de44be72/src/index.d.ts#L77) is defined as `string` only. Also, checking the [code](https://github.com/nearform/fast-jwt/blob/688f2373df8e1c0a5d76c421bb5510d0de44be72/src/signer.js#L263), it seems like the array is allowed, too.

Just wondering if it's just a type error in the definition.

**Comment by simoneb** [comment]
It's most likely a typing error. Would you like to send a PR to fix it?
