### ISSUE TITLE
wrap caching around  a library like jose

### ISSUE THREAD

**Issue by eyousefifar** [nearform/fast-jwt#27]
By looking at benchmarks I think most of performance is coming from caching verified token in LRU Cache ( I didn't do profiling myself on any jwt library ). isn't it better to just wrap caching around jose or node-jsonwebtoken ( i chose jose cause of eddsa. although jsonwebtoken is widely used and has many starrs,  I didn't like the code ). I would appreciate some insight about this.
Thanks

**Comment by mcollina** [comment]
It is not possible to plug caching in jsonwebtoken due to how the api and code is structured. Essentially we need a factory to build/wrap the cache.

Regarding jose, we were not aware of it when we started this effort. It will require a similar API change to adopt this technique.

**Comment by eyousefifar** [comment]
based on what I've read in verifier, saving a hashed token as key in cache and it's payload such as token valid time etc ( or complete token ) as value is the way cache works sort of. 
I don't know about other optimization being done in this library or will be done ( considering you're the guys from the awesome fastify package ), but this caching technique can be exposed to other jwt packages. maybe as separate package. I know it's not as neat as what you're doing. I'm just curious here

**Comment by mcollina** [comment]
> but this caching technique can be exposed to other jwt packages

In order to have the desired performance improvement it must be done in a specific step of the jwt verification process. There is no way to plug code into that specific step without significant change in those libraries.
