### ISSUE TITLE
Verifier async key function errors are always cached

### ISSUE THREAD

**Issue by joeldn** [nearform/fast-jwt#275]
First of all thanks for the work that's been put into this library! I'm using it in a project and it's been great apart from one little issue:

I'm using the `createVerifier` function and got it set up with cache enabled and an async `key` function which periodically fetches public keys from a different service. Sometimes this fetch fails and in the current version of the library this error is cached and there is no way of forcing a refresh for this specific token, which means calls to my service will fail authentication for as long as my cacheTTL is set.

The only way to work around this seems to be implementing my own cache or do something really hacky like shimming the `cache.set` function to not do anything when the value is a TokenError, but both are not ideal. 

Is it maybe possible to add something like a `cacheOnAsyncError` option with a default set to `false` that allows for conditionally handeling the getAsyncKey function caching on error?

More than happy to create a PR for it if something like this is desired. Thanks!

**Comment by marco-ippolito** [comment]
I think it is a useful feature to add, feel free to create a PR!
I don't know if there is a use case where caching error responses is desired as it is usually an anti-pattern, so I'm just wondering whether to disable it all together.

**Comment by marco-ippolito** [comment]
On the other hand if we don't cache the response, the server will retry on the next request which will could also be a problem. It requires a more refined solution
