### ISSUE TITLE
Experimental

### ISSUE THREAD

**Issue by robmcguinness** [nearform/fast-jwt#28]
The `README` states "This module is experimental". What is needed to push this library to a non-experimental phase? I recently integrated `fast-jwt` with `hapi` for use in our microservices and all unit and integration tests passed. I love the simplicity of this lib and would be willing to help move this effort along.

**Comment by mcollina** [comment]
I would say some report of production usage. We are putting this in production right now ourself, however it would be interesting to have some other feedback as well.

An independent security analysis would speed this process up quite a bit.

**Comment by robmcguinness** [comment]
FYI we are in production. I'll report back any issues.

**Comment by fergusean** [comment]
FYI I've also been using this in production for 6 months.
