### ISSUE TITLE
Expired token is being accepted

### ISSUE THREAD

**Issue by jacklagare** [nearform/fast-jwt#29]
We recently integrated `fast-jwt` with an API implemented in `restify` due to some performance issues in token verification. However, the tokens even though expired are still being allowed. See below the implementation:

```
const verifyWithCallback = createVerifier({ 
                    key: getKey, 
                    complete: true,
                    cache: true,
                    ignoreExpiration: false,
                    algorithms: ['HS256','HS384', 'HS512','RS256']
                })
                
                let encodedToken = token
                console.log('type: '+typeof(encodedToken))

                await verifyWithCallback(encodedToken, (err, sections) => {
                    if(err){
                        console.log(err)
                        res.send(400)
                        return
                    }
                    else{
                        const decode = createDecoder()
                        let payload = decode(encodedToken)
                       ...
```

Looking at the `verify,js` file, I saw a line there that terminates the execution if the type of the payload is string. I'm not sure if that has a bearing.

**Comment by mcollina** [comment]
Can you please include a full snippet? Thanks, we'll fix asap.
If you have a PR ready, send a PR!

**Comment by jacklagare** [comment]
Hi @mcollina. See below the code that I use to verify and decode the token. We have WSO2 Identity Server as the provider of the token.

```
const r = req
let token = req.headers['x-access-token'] || req.headers['authorization']
				
token = token.slice(7,token.length).trimLeft().trim()
            
if (token.length <= 0) {
    res.send(401)
    return
}

try {
    
    const verifyWithCallback = createVerifier({ 
        key: getKey, 
        complete: true,
        cache: true,
        ignoreExpiration: false,
        algorithms: ['HS256','HS384', 'HS512','RS256']
    })
    
    let encodedToken = token
    console.log('type: '+typeof(encodedToken))

    await verifyWithCallback(encodedToken, (err, sections) => {
        if(err){
            res.send(401)
            return
        }
        else{
            return next()
        }
    })
}

catch(err){
    res.send(401)
    return
}
```

See below a sample payload of the token. Sensitive data has been removed. This particular token is being accepted even though it's way past the expiry.
```
{
  "at_hash": "xxxx",
  "http://wso2.org/claims/gender": "male",
  "http://wso2.org/claims/username": "xxxx",
  "sub": "xxxx",
  "http://wso2.org/claims/photourl": "xxxx",
  "amr": [
    "SAMLSSOAuthenticator"
  ],
  "iss": "xxxx",
  "http://wso2.org/claims/givenname": "xxxx",
  "http://wso2.org/claims/identity/emailVerified": "true",
  "aud": "lxbtzpbN01JC0NMHDzA7UpfNDAYa",
  "c_hash": "xxxx",
  "nbf": 1597531796,
  "http://wso2.org/claims/local": "en",
  "http://wso2.org/claims/fullname": "xxx)",
  "azp": "xxxx",
  "http://wso2.org/claims/emailaddress": "xxx",
  "http://wso2.org/claims/lastname": "xxxx",
  "http://wso2.org/claims/url": "xxxxxx",
  "exp": 1597535396,
  "iat": 1597531796
}
```

In the `verify.js` file, in line 177. I see that the condition evaluates to TRUE hence the execution stops. Now, I'm not sure I understand fully what this line is suppose to do:

```
if (typeof payload === 'string') {
    return
  }
```

I'm still trying to figure out the code but if I can see something I can help with, I'll make sure to send a PR.

**Comment by mcollina** [comment]
The best plan of action would be for you to send a failing example or unit test that I can use to reproduce things locally. If that also includes a fix, that'd be amazing.

**Comment by mcollina** [comment]
(By full snippet I mean something that I can run).

**Comment by mcollina** [comment]
A few folks have asked me if this is related to caching... it's not.

**Comment by mcollina** [comment]
In https://github.com/nearform/fast-jwt/blob/4f7fbfb2399776487e9f959789961e45c8a9216c/src/verifier.js#L174-L176, we check if the payload is a `string`. If it has a string, it cannot include any claims, so we cannot verify them. You might want to add a `console.log(payload)` before that if and see what is exactly being decoded.

**Comment by mcollina** [comment]
Closing as the issue should be fixed / there should not be an error instead.

**Comment by jacklagare** [comment]
Sorry I wasn't able to respond immediately. Just wanted to tell you @mcollina that upgrading to 0.2.0 fixed the problem. Thanks!
