### ISSUE TITLE
Type recognition is incorrect

### ISSUE THREAD

**Issue by awdr74100** [nearform/fast-jwt#305]
Consider the following example:

```ts
import { createSigner } from "fast-jwt";

async function test() {
  const signWithPromise = createSigner({ key: async () => "secret" });

  const token = await signWithPromise({ a: 1, b: 2, c: 3 });
}
```

It seems that `signWithPromise` cannot be recognized as return a `Promise<string>` target:

![螢幕擷取畫面 2023-02-15 212000](https://user-images.githubusercontent.com/47501692/219038604-324bf10c-93fb-4ea6-bbea-0e780d6aa29c.png)

Cause VSCode to prompt that the `await` has no effect.

Reproduction step:

```shell
cd ./demo
pnpm init
pnpm add typescript -D # pnpm tsc --init
pnpm add fast-jwt -P
```

Am I wrong about something? Thanks to anyone who can help!

**Comment by RomuloVitoi** [comment]
Hello @awdr74100 , could you confirm which version of fast-jwt do you have installed or provide a repo with the code that you have shown? I was not able to reproduce this:
![Screenshot 2023-02-16 at 11 08 18](https://user-images.githubusercontent.com/1702334/219387569-58eb9460-a5d9-4eae-af4e-f59205e22063.png)

**Comment by awdr74100** [comment]
```shell
code --version # 1.75.1
```
```json
{
  "devDependencies": {
    "typescript": "^4.9.5"
  },
  "dependencies": {
    "fast-jwt": "^2.2.0"
  }
}
```

Repo: https://github.com/awdr74100/fast-jwt-demo

Problems still happen. Thanks for your help!

**Comment by RomuloVitoi** [comment]
@awdr74100 That is happening because your project is missing the node types, thus `Buffer` resolves as `any` and causes a conflict with the method overload. Adding the `@types/node` package to your project solves the issue:

```sh
pnpm add @types/node -D
```

**Comment by awdr74100** [comment]
It was such a stupid mistake! Thank you for your kind help!

Many times it is the `ts-node` package that reminds me to install the `@types/node` package...
