### ISSUE TITLE
Provide fully decoded jwt object to key callback

### ISSUE THREAD

**Issue by hauptmedia** [nearform/fast-jwt#330]
Hi,

it would really simplify my integration scenario if the complete decoded JWT object is passed to the key callback here:

https://github.com/nearform/fast-jwt/blob/master/src/verifier.js#L327

I want to dynamically resolve the key based on the issuer (iss) and need to have access to the payload.

Unfortunately this would be a breaking change because the header is now not the root level object anymore. Perhaps it could make sense to make this configurable?

What do you think?

Cheers,

Julian

**Comment by guilhermelimak** [comment]
@hauptmedia Can you try [this PR](https://github.com/nearform/fast-jwt/pull/335) and see if it works properly for your use case?

**Comment by hauptmedia** [comment]
Works great, thank you
