### ISSUE TITLE
TypeScript issue with verifier KeyFetcher 

### ISSUE THREAD

**Issue by qoomon** [nearform/fast-jwt#406]
Currently I get the error `Binding element  header  implicitly has an  any  type` for following code.
```ts
const verifyWith = jwt.createVerifier({
  key: async ({header}) => jwks.getPublicKey({
    kid: header.kid,
    alg: header.alg,
    domain: 'https://example.com',
  }),
})
```
and I can't fix it by explicitly set type to `DecodedJwt` because it is not exported
```ts
  key: async ({header}: DecodedJwt) => jwks.getPublicKey({
```

Do you have an advise how to solve that?

**Comment by simoneb** [comment]
would you like to send a PR to fix it?

**Comment by qoomon** [comment]
Actually I don't know how to fix that. For me everything seems right :-/

**Comment by simoneb** [comment]
Didn't you send a PR just now?

**Comment by qoomon** [comment]
@simoneb yes, however I don't know why it works in `type.spec.ts` without my fix :-D

**Comment by qoomon** [comment]
Nevermind its working now
