### ISSUE TITLE
Node 22 support

### ISSUE THREAD

**Issue by kibertoad** [nearform/fast-jwt#425]
Currently package.json requires Node <22. Is there any particular reason for that? Wonder if upper boundary could be removed altogether, if there are no clear expectation that future Node versions will definitely break the compatibility.

**Comment by simoneb** [comment]
No specific reason I suppose, the only thing that comes to mind is the logic used by the CI workflow to choose Node versions to tests against. Leaving the >= condition should be good

**Comment by kibertoad** [comment]
Should I send a PR for that, or you would do that?

**Comment by simoneb** [comment]
Go ahead :)

**Comment by kibertoad** [comment]
done!

**Comment by kibertoad** [comment]
@simoneb Any chance you could release a new patch version? Currently this is the only warning we get on Node 22
