### ISSUE TITLE
Types for JWT header do not accept additional arbitrary fields

### ISSUE THREAD

**Issue by Akallabet** [nearform/fast-jwt#475]
**Problem**
[createSigner](https://github.com/nearform/fast-jwt/blob/master/src/signer.js#L191) correctly accepts additional arbitrary fields to the header.
However the [interface for the JwtHeader ](https://github.com/nearform/fast-jwt/blob/master/src/index.d.ts#L83) doesn't.

**Example**
```
import { createSigner } from "fast-jwt";

const signer = createSigner({
	key: "secret",
	algorithm: "HS256",
	header: { custom: "header" },
});

// ts error:
1. No overload matches this call.
     Overload 1 of 2, '(options?: Partial<SignerOptions & { key: any; }> | undefined): (payload: any) => string', gave the following error.
       Type '{ custom: string; }' is not assignable to type 'JwtHeader'.
         Object literal may only specify known properties, and 'custom' does not exist in type 'JwtHeader'. [2769]

```
**Current workaround**
I can use //@ts-ignore to force TS to like the additional field.

**Proposed solution**
We can add a generic type to `JwtHeader`
I would be happy to submit a PR in case

**Comment by simoneb** [comment]
Feel free to send a PR!
