### ISSUE TITLE
Breaking Change included as a patch version

### ISSUE THREAD

**Issue by vidarc** [nearform/fast-jwt#514]
Due to https://github.com/nearform/fast-jwt/pull/502 and the engines increase (from 16 => 20), the latest patch versions of this package should have been considered a breaking change. This dropping of support for Node <= 20 doesn't appear to be documented either.

specifically - https://github.com/nearform/fast-jwt/pull/502/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L80

**Comment by simoneb** [comment]
Thanks for reporting. I've deprecated 4.0.6 and published 5.0.0.

@ilteoood be careful when making such changes, this semver major change was done in a PR whose semver tag was chore: https://github.com/nearform/fast-jwt/pull/509

**Comment by ilteoood** [comment]
> Thanks for reporting. I've deprecated 4.0.6 and published 5.0.0.
> 
> @ilteoood be careful when making such changes, this semver major change was done in a PR whose semver tag was chore: #509

I thought it would check the content of each commit.
In fact, I added the `breaking` prefix where it has been made: https://github.com/nearform/fast-jwt/pull/502/commits/35e56cbad18c9b77f38e03648b38cceacf82d1a9
