### ISSUE TITLE
Setting complete to true in verifier does not return the input

### ISSUE THREAD

**Issue by timjam** [nearform/fast-jwt#521]
Hi!

First of all thanks for creating a great JWT library.

I wanted to create a new Passport JWT strategy using your JWT library, because the current most used strategy library does not support EdDSA algorithms. When playing around with it, it looks like in contrary what the docs say setting the `complete: true` in verifier settings does not return the original input token. Instead it seems to only return the `header`, `payload` and `signature`

Also in case you want to check it out, here's the package
https://www.npmjs.com/package/passport-fast-jwt

**Comment by simoneb** [comment]
Thanks for reporting! Weird, because according to our tests it seems that setting complete to true does indeed return what is documented. See [here](https://github.com/nearform/fast-jwt/blob/master/test/decoder.spec.js#L17).

Thoughts?

**Comment by timjam** [comment]
Hmm I have to recheck this and make sure I am using the latest version of the package. I'll come back in a short moment

**Comment by timjam** [comment]
To me it looks like the decoder returns the input, but the verifier does not. Should it be like that?

I was able to verify that your verifier at least does not return the input

```typescript
const sign = createSigner({
    key: async () => "secret",
  })

const token = sign({ sub: "123" })

const verify = createVerifier({
  key: async () => "secret"
  complete: true,
})

const sections = verify(token)

// Here the sections does not contain the input property

```

**Comment by simoneb** [comment]
So it seems, so you're right that the doc is misleading.

**Comment by timjam** [comment]
Great. Thanks for a very very fast reaction and good to have the docs fixed

**Comment by timjam** [comment]
You may want to add the input also into the types.

```typescript
type DecodedJwt = {
  header: Record<string, any>
  payload: any
  signature: string
  // input is missing here
}
```
