### ISSUE TITLE
Support custom exp claim

### ISSUE THREAD

**Issue by edsondewes** [nearform/fast-jwt#58]
Hi!

I'm working on a feature where I need to set a different expiration for each token I sign.
I tried to do set a "exp" field but it didn't work:
```javascript
const { createSigner } = require('fast-jwt')
const signSync = createSigner({ key: 'secret' })
const token = signSync({
  a: 1,
  exp: Math.floor(Date.now() / 1000) + (60 * 60),
})
```

Looking at the code, I saw that "exp" is overwritten by "undefined" if "expiresIn" is not set.
```javascript
const finalPayload = {
    ...payload,
    ...fixedPayload,
    iat: noTimestamp ? undefined : Math.floor(iat / 1000),
    exp: expiresIn ? Math.floor((iat + expiresIn) / 1000) : undefined,
    nbf: notBefore ? Math.floor((iat + notBefore) / 1000) : undefined
  }
```

Would it be possible to change the "finalPayload" to `exp: expiresIn? Math.floor ((iat + expiresIn) / 1000): payload.exp` or have some other way of passing a custom "exp"?

Thanks!

**Comment by mcollina** [comment]
I think it's a good idea! Would you like to send a PR to implement this feature?

**Comment by edsondewes** [comment]
Sure! I will try to send this weekend.
Thanks

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
