### ISSUE TITLE
Add a cache for async keys

### ISSUE THREAD

**Issue by mcollina** [nearform/fast-jwt#62]
in `createVerified`, we accept a `key` as a function. However we do not cache the fetched key. Adding caching would likely speed things up quite a bit in case of remote jwks keys.

**Comment by sameer-coder** [comment]
@mcollina  There is a package called [get-jwt](https://github.com/nearform/get-jwks) developed by Nearform in which we have already implemented caching for keys as a function and it integrates very well with fast-jwt too. Do you think we can just use get-jwt along with fast-jwt whenever caching is required?

**Comment by mcollina** [comment]
I think writing an example on how to use the two packages together is enough!

**Comment by simoneb** [comment]
We have that in the get-jwks docs but it needs to be updated to represent a more realistic scenario (dynamic token instead of static). @sameer-coder can you please take care of that?

**Comment by sameer-coder** [comment]
Async keys are supported by get-jwks package and it supports caching too. You can refer get-jwks docs for examples on integration with fast-jwt. Closing this issue.
