### ISSUE TITLE
Support for JWKS public keys

### ISSUE THREAD

**Issue by mcollina** [nearform/fast-jwt#63]
We should support fetching from a JWKS url and cache things.

https://github.com/nearform/fast-jwt/issues/62 for the caching bit.

**Comment by simoneb** [comment]
I believe there's an implementation of support for JWKS specific to auth0 in https://github.com/nearform/fastify-auth0-verify.

We also probably want to have this feature integrated in https://github.com/fastify/fastify-jwt but the implementation should live in a standalone library so it can be used outside of fastify-jwt

**Comment by simoneb** [comment]
This is the AWS Cognito documentation about how to validate the JWTs it generates, which also uses JWKS. https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-verifying-a-jwt.html

**Comment by p16** [comment]
To add more context to this issue:

- we need a separate package for `jwks` (not inside `fast-jwt`)
- `fastify-auth0-verify` and `fastify-jwt` would use that new package 
- `fast-jwt` conceptually is like `jsonwebtoken`, but it's not reasonable to assume we can replace `jsonwebtoken` inside `fastify-jwt`: `fast-jwt` is not at that level yet.

The package should do 

- fetch jwks
- having a way to return you the secret that matches `kid` and `alg`
- validate a jwt against that secret

**Comment by mcollina** [comment]
I would avoid:

> validate a jwt against that secret

and leave it to jsonwebtoken and this module.

**Comment by p16** [comment]
What has been done up until now:
- We created the [jwks-fetch](https://github.com/nearform/jwks-fetch) repo and move there the feature discussed with @simoneb and @mcollina (from [here](https://github.com/nearform/fastify-auth0-verify/blob/master/index.js#L81))
- the `jwks-fetch` implementation should be addressing all the requests in this ticket (partially also https://github.com/nearform/fast-jwt/issues/62)

What is left to do:
- use `jwks-fetch` in `fastify-auth0-verify`
- use `jwks-fetch` in `fast-jwt`

**Comment by simoneb** [comment]
@conor909 let's do this first:

- use jwks-fetch in fast-jwt

Which requires that jwks-fetch is published to npm, CI is setup and so on

**Comment by mcollina** [comment]
The best approach would be:

```js
const  {createVerifier} = require('fast-jwt')
const buildJwks = require('jwks-fetch')
const verify = createVerifier({ key: buildJwks() })
```

Essentially making the two modules loosely couple (but working well together).

**Comment by simoneb** [comment]
there is now a hint about how to do this via get-jwks [here](https://github.com/nearform/fast-jwt#jwks). It's not exactly the one liner you had in mind but it's not too bad either

**Comment by sameer-coder** [comment]
JWKS public keys are supported by get-jwks package. Please refer get-jwks docs for examples on integration with fast-jwt. Closing this issue.
